[package]
name = "alloy-unit-macros-impl"
version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true

[dependencies]
alloy-primitives.workspace = true
proc-macro2 = "1"
quote = "1"
syn = "2"

[lib]
proc-macro = true
